In [1]:
import numpy as np

Напишите программу NumPy для преобразования заданного массива в байты и загрузите его как массив.  

In [2]:
a = np.a([1, 2, 3, 4, 5, 6])
print(a)
a_bytes = a.tobytes()
print(a_bytes)
a2 = np.frombuffer(a_bytes, dtype=a.dtype)
print(a2)

[1 2 3 4 5 6]
b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00'
[1 2 3 4 5 6]


Напишите программу NumPy для создания массива из 10 нулей, 10 единиц, 10 пятерок.

In [3]:
a=np.zeros(10)
print(a)
a=np.ones(10)
print(a)
a=np.ones(10)*5
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Напишите программу NumPy для создания вектора длиной 5, заполненного произвольными целыми числами от 0 до 10

In [4]:
a = np.random.randint(0, 11, 5)
print(a)

[1 1 2 3 2]


Напишите программу NumPy для вычисления внутреннего произведения двух заданных векторов. 

In [5]:
x = np.array([4, 5])
y = np.array([7, 10])
print(x)
print(y)
print(np.dot(x, y))

[4 5]
[ 7 10]
78


Напишите программу NumPy для создания матрицы 3х3 со значениями от 2 до 10.

In [6]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Напишите программу NumPy для создания пустого и полного массива.

In [7]:
x = np.empty((3,4))
print(x)
y = np.full((3,3),6)
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Напишите программу NumPy, чтобы найти объединение двух массивов. Union вернет уникальный отсортированный массив значений, которые находятся в любом из двух входных массивов.

In [8]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print(array1)
array2 = [10, 30, 40, 50, 70]
print(array2)
print(np.union1d(array1, array2))

[ 0 10 20 40 60 80]
[10, 30, 40, 50, 70]
[ 0 10 20 30 40 50 60 70 80]


 Напишите программу NumPy, чтобы найти объем памяти массива NumPy.

In [9]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


Напишите программу NumPy для создания двумерного массива, диагональ которого равна [4, 5, 6, 8] и 0 где-либо еще.

In [10]:
x =  np.diagflat([4, 5, 6, 8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


Напишите программу NumPy для перемещения указанной оси назад, пока она не окажется в заданной позиции.

In [16]:
x = np.ones((2,3,4,5))
print(np.rollaxis(x, 2, 0).shape)

(4, 2, 3, 5)


Напишите программу NumPy, чтобы получить количество ненулевых элементов в массиве.

In [17]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print(x)
print(np.count_nonzero(x))

[[ 0 10 20]
 [20 30 40]]
5


Напишите программу NumPy для создания массива (3, 4) формы, умножьте значение каждого элемента на 3 и отобразите новый массив.

In [18]:
x= np.arange(12).reshape(3, 4)
print(x)
for a in np.nditer(x, op_flags=['readwrite']):
    a[...] = 3 * a
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


Напишите программу NumPy для преобразования массива чисел с плавающей точкой в массив целых чисел

In [19]:
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print(x)
print(x.astype(int))

[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
[[12 12]
 [ 2  7]
 [25 36]]


Напишите программу NumPy, чтобы получить величину вектора в numpy.

In [20]:
x = np.array([1,2,3,4,5])
print(x)
print(np.linalg.norm(x))

[1 2 3 4 5]
7.416198487095663


Напишите программу NumPy для расчета евклидова расстояния.

In [21]:
from scipy.spatial import distance
p1 = (1, 2, 3)
p2 = (4, 5, 6)
d = distance.euclidean(p1, p2)
print(d)

5.196152422706632


Напишите программу NumPy для построения массива всех комбинаций из трех числовых массивов.

In [22]:
x = [1, 2, 3]
y = [4, 5]
z = [6, 7]
print(x)
print(y)
print(z)
new_array = np.array(np.meshgrid(x, y, z)).T.reshape(-1,3)
print(new_array)

[1, 2, 3]
[4, 5]
[6, 7]
[[1 4 6]
 [1 5 6]
 [2 4 6]
 [2 5 6]
 [3 4 6]
 [3 5 6]
 [1 4 7]
 [1 5 7]
 [2 4 7]
 [2 5 7]
 [3 4 7]
 [3 5 7]]


Напишите программу NumPy для создания двух массивов, когда размер больше или меньше заданного массива.

In [23]:
x = np.arange(16).reshape(4,4)
print(x)
new_array1 = np.resize(x,(2,2))
print(new_array1)
new_array2 = np.resize(x,(6,6))
print(new_array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15  0  1]
 [ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15  0  1  2  3]]


Напишите программу NumPy для подсчета количества измерений, количества элементов и количества байтов для каждого элемента в данном массиве. 

In [24]:
x = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
print(x)
print(x.ndim)
print(x.size)
print(x.itemsize)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
2
24
8


Напишите программу NumPy для извлечения первого элемента второй строки и четвертого элемента четвертой строки из заданного (4x4) массива.

In [25]:
arra_data = np.arange(0,16).reshape((4, 4))
print(arra_data)
print(arra_data[[1,3], [0,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 4 15]


Напишите программу NumPy для извлечения верхней треугольной части матрицы NumPy.

In [26]:
num = np.arange(18)
arr1 = np.reshape(num, [6, 3])
print(arr1)
result  = arr1[np.triu_indices(3)]
print(result)
result  = arr1[np.triu_indices(2)]
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[0 1 2 4 5 8]
[0 1 4]


Напишите программу NumPy для вычисления перекрестного произведения двух заданных векторов.

In [27]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print(result1)
print(result2)

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[ 2 -3]
[-2  3]


Напишите программу NumPy для расчета QR-разложения данной матрицы

In [28]:
m = np.array([[1,2],[3,4]])
print(m)
result =  np.linalg.qr(m)
print(result)

[[1 2]
 [3 4]]
(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


Напишите программу NumPy для создания массива 3x3x3 со случайными значениями.

In [29]:
x = np.random.random((3,3,3))
print(x)

[[[0.97011078 0.75555853 0.26259649]
  [0.80704668 0.6436173  0.85663431]
  [0.24546322 0.59805397 0.67637942]]

 [[0.08530689 0.76906985 0.84578665]
  [0.59446133 0.64209853 0.26983545]
  [0.81285597 0.9885349  0.41683281]]

 [[0.6236616  0.88750694 0.30335082]
  [0.05199659 0.67024858 0.22772363]
  [0.32921129 0.63670736 0.09075902]]]


Напишите программу NumPy, чтобы найти наиболее частое значение в массиве.

In [31]:
x = np.random.randint(0, 10, 40)
print(x)
print(np.bincount(x).argmax())

[2 6 6 8 8 3 8 3 8 7 9 0 7 5 5 4 2 1 8 5 9 5 9 8 5 7 4 2 1 1 4 6 6 2 0 1 9
 1 1 6]
1


Напишите программу NumPy для создания структурированного массива из заданного имени ученика, роста, класса и их типов данных. Теперь сортируйте по классу, затем по высоте, если класс равен

In [32]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)   
print(students)
print(np.sort(students, order=['class', 'height']))

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


Напишите программу NumPy, чтобы получить истинное деление входов массива элементов.

In [33]:
x = np.arange(10)
print(x)
print(np.true_divide(x, 3))

[0 1 2 3 4 5 6 7 8 9]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


Напишите программу NumPy для создания внутреннего продукта из двух массивов.

In [34]:
x = np.arange(24).reshape((2,3,4))
print(x)
y = np.arange(4)
print(y)
print(np.inner(x, y))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0 1 2 3]
[[ 14  38  62]
 [ 86 110 134]]


Напишите программу NumPy для преобразования углов из радианов в градусы для всех элементов в данном массиве.  
Входные данные: [-np.pi, -np.pi / 2, np.pi / 2, np.pi]
Образец вывода:
[-180. -90. 90. 180.]


In [35]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
r1 = np.degrees(x)
r2 = np.rad2deg(x)
assert np.array_equiv(r1, r2)
print(r1)

[-180.  -90.   90.  180.]


 Напишите программу NumPy для вычисления 2p для всех элементов в данном массиве.  
Образец вывода:
Исходный массив:
[1. 2. 3. 4.]
2 ^ p для всех элементов указанного массива:
[2. 4. 8. 16.]


In [36]:
x = np.array([1., 2., 3., 4.], np.float32)
print(x)
r1 = np.exp2(x)
r2 = 2 ** x
assert np.allclose(r1, r2)
print(r1)

[1. 2. 3. 4.]
[ 2.  4.  8. 16.]


Напишите программу NumPy, чтобы вычислить разницу между максимальным и минимальным значениями данного массива вдоль второй оси.  
Ожидаемый результат:
Исходный массив:
[[0 1 2 3 4 5]
[6 7 8 9 10 11]]
Разница между максимальным и минимальным значениями указанного массива:
[5 5]


In [37]:
x = np.arange(12).reshape((2, 6))
print(x)
r1 = np.ptp(x, 1)
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print(r1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[5 5]


Напишите программу на Python для подсчета количества вхождений каждого значения в данный массив неотрицательных целых чисел. Перейти к редактору
Примечание: функция bincount () считает количество вхождений каждого значения в массив неотрицательных целых чисел в диапазоне массива между минимальным и максимальным значениями, включая значения, которые не встречались.
Пример вывода:
Исходный массив:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
Количество вхождений каждого значения в массиве:
[1 3 2 0 1 0 1 1]

In [38]:
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print(array1)
print(np.bincount(array1))

[0, 1, 6, 1, 4, 1, 2, 2, 7]
[1 3 2 0 1 0 1 1]


Напишите программу NumPy для подсчета количества дней определенного месяца.  
Ожидаемый результат:

Количество дней, февраль 2016 года:
29 дней

Количество дней, февраль 2017 года:
28 дней

Количество дней, февраль 2018 года:
28 дней


In [39]:
print("Number of days, February, 2016: ")
print(np.datetime64('2016-03-01') - np.datetime64('2016-02-01'))
print("Number of days, February, 2017: ")
print(np.datetime64('2017-03-01') - np.datetime64('2017-02-01'))
print("Number of days, February, 2018: ")
print(np.datetime64('2018-03-01') - np.datetime64('2018-02-01'))

Number of days, February, 2016: 
29 days
Number of days, February, 2017: 
28 days
Number of days, February, 2018: 
28 days


Напишите программу NumPy, в которой прописными буквами будут прописные буквы, строчные буквы, прописные буквы, прописные буквы, заглавные буквы всех элементов данного массива.  
Ожидаемый результат:

Оригинальный массив:
['python' 'PHP' 'java' 'C ++']

С большой буквы: ['Python' 'Php' 'Java' 'C ++']

Понижено: ['python' 'php' 'java' 'c ++']

Uppered: ['PYTHON' 'PHP' 'JAVA' 'C ++']

Swapcased: ['PYTHON' 'php' 'JAVA' 'c ++']

Titlecased: ['Python' 'Php' 'Java' 'C ++']


In [41]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=str)
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


Напишите программу NumPy, чтобы заменить «PHP» на «Python» в элементе данного массива.  
Пример вывода:

Оригинальный массив:
['PHP Упражнения, Практика, Решение']

Новый массив:
['Упражнения на Python, практика, решение']


In [44]:
x = np.array(['PHP Упражнения, Практика, Решение'], dtype=str)
print(x)
r = np.char.replace(x, "PHP", "Python")
print(r)

['PHP Упражнения, Практика, Решение']
['Python Упражнения, Практика, Решение']
